# Generated by Django 4.2.1 on 2023-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('GPA', models.FloatField()),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('level', models.IntegerField()),
                ('status', models.BooleanField()),
                ('department', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=255)),
                ('mobilePhone', models.CharField(max_length=255)),
            ],
        ),
    ]
